sudo:required
services:
  - docker

before_install:
  - docker build -t kaushikbarun/docker-react -f Dockerfile.dev .

script:
  - docker run kaushikbarun/docker-react npm run test -- --coverage